### ISSUE TITLE
Max hit is incorrect

### ISSUE THREAD

**Issue by luna-duclos** [Matt12yearslater/max-hit#1]
My max hit on a dummy with this gear is a 48, but according to the plugin, it is a 42:

![image](https://user-images.githubusercontent.com/5576448/90424495-85b71e00-e0be-11ea-96cc-e6ce602b7ddc.png)

Rigour is on and a divine ranging pot was used with 99 ranged.

**Comment by Matt12yearslater** [comment]
Is your max hit dummy the normal version or the undead type?

**Comment by luna-duclos** [comment]
The undead/slayer dummy type

**Comment by Matt12yearslater** [comment]
That’s what I was thinking; I intentionally left some bonuses/situations out, such as slayer helm, wilderness weapons, ruby bolts (e), etc., in order to avoid clutter as those are fairly specific cases, whereas I’d hoped for this plugin to be more geared for general situations.
